db:
  server.name: "J-ROSENGURTT\\SQLEXPRESS"
  database.name: "FusionRequest"
  username: "sonic"
  password: "sonic"

http:
  port: "8093"
  host: "0.0.0.0"
  basepath: "/"
  
https:
  port: "8092"
  host: "0.0.0.0"
  basepath: "/"

time.setter.web:
  host: "localhost"
  port: "5000"
  timeout: "10000"
  
certificate:
  keystore: "faky.keystore"
  password: "password"
  
fusion:
  url: "local.fusion.aero"
  port: "80"
  timeout: "42000"
  
real.time.server:
  url: "http://worldtimeapi.org/api/timezone/Europe/London"
  host: "worldtimeapi.org"
  timeout: "30000"
  
fusiontester.timeout: "80000"