#%RAML 1.0
title: FusionTester
version: v1
description: "Reads the Fusion requests from a table that has the logs of Fusion sesions and sends the requests to a Fusion service. It then compares the response from the Fusion service and compares it with the response in the log."

/fusiontester/execution/{test-id}:
  post:
    description: Starts/restarts/stops a test
    body:
      application/json:
        type: object
        properties:
          Action:
            enum: [start, stop]
            required: true
            description: Indicates if a test has to be started or stopped

    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              message:
                type: string
                example: |
                  {
                    "message" : "Test started"
                  }

/fusiontester/tests:
  get:
    description: Returns a list of tests. The tests returned can be filtered and paged.
    queryParameters:
      date-from:
        type: string
        required: false
        description: filters out tests done before this date
        example: '2019-05-04'
      date-to:
        type: string
        required: false
        description: filters out tests done after this date
        example: '2019-05-04'
      page-size:
        type: integer
        description: Used for pagination. The number of records per page.
        required: false
        default: 10
        example: 12
      page:
        type: integer
        description: Used for pagination. The page number to return.
        required: false
        default: 1
        example: 3
        
    responses:
      200:
        body:
          application/json:
            type: array
            items: !include types/test.raml
  post:
    description: Used for create new tests
    body:
      application/json:
        type: object
        properties:
          TestName:
            type: string 
            required: true
            description: Some meaningful name given to the test
            example: Regresion test for bug fix 12345
          TestDescription:
            type: string | nil
            required: false
            description: Text that provides information about the test
            example: Verify that the bug fix hasn't broken boarding for Jetblue
          TestCreator: 
            type: string | nil
            description: The name of the person that created the test
          IncludeAirports:
            type:  string[]
            description: An array with the 3 letter codes of the airports to include. An empty array means include all
            example: ["LHR","STN","EDI"]
          IncludeAirlines:
            type: string[]
            description: An array with the 2 letter codes of the airlines to include. An empty array means include all
            example: ["FR","BE","BA","LS"]
          FromDate:
            type: string | nil
            description: Used to filter the records to include in the test. This is the lower limit
            example: "2019-04-07 23:00:08"
          ToDate:
            type: string | nil
            description: Used to filter the records to include in the test. This is the upper limit
            example: "2019-09-07 02:00:08"
          IncludeFusionRequestTypes:
            type: string[]
            description: An array with the request types to include. An empty array means include all
            example: ["GetReservationByNativeReference", "QuoteBag"]

    responses:
        200:
          body:
            application/json:
              type: object
              properties:
                result:
                  type: string
                  example: "success"
                data:
                  type: object
                  example: |
                    {
                        "TestId": 23
                    }



/fusiontester/tests/{test-id}:
  get:
    description: Returns the details of a test
      
    responses:
      200:
        body:
          application/json:
            type: object
            example: |
              {
                "CreationDateTime": "2019-09-11T13:35:33.1",
                "RecordsProcessed": 18,
                "TestName": "Bug fix 1234",
                "NumberOfErrors": 18,
                "FromDate": "1900-01-01T00:00:00",
                "IncludeFusionRequestTypes": "%",
                "ToDate": "3000-01-01T00:00:00",
                "TestCreator": "",
                "IncludeAirports": "%",
                "TestDescription": "Regression test for bug fix for Easyjet",
                "LastActiveDateTime": "2019-09-11T16:33:02.23",
                "IncludeAirlines": "'W6'",
                "EndDateTime": "2019-09-11T16:33:15.81",
                "TestId": 64,
                "StartDateTime": "2019-09-11T16:29:03.303"
              }

  put:
    description: Used to update existing tests
    body:
      application/json:
        type: object
        properties:
          TestName:
            type: string 
            required: true
            description: Some meaningful name given to the test
            example: Regresion test for bug fix 12345
          TestDescription:
            type: string | nil
            required: false
            description: Text that provides information about the test
            example: Verify that the bug fix hasn't broken boarding for Jetblue
          TestCreator: 
            type: string | nil
            description: The name of the person that created the test
          IncludeAirports:
            type:  string[]
            description: An array with the 3 letter codes of the airports to include. An empty array means include all
            example: ["LHR","STN","EDI"]
          IncludeAirlines:
            type: string[]
            description: An array with the 2 letter codes of the airlines to include. An empty array means include all
            example: ["FR","BE","BA","LS"]
          FromDate:
            type: string | nil
            description: Used to filter the records to include in the test. This is the lower limit
            example: "2019-04-07 23:00:08"
          ToDate:
            type: string | nil
            description: Used to filter the records to include in the test. This is the upper limit
            example: "2019-09-07 02:00:08"
          IncludeFusionRequestTypes:
            type: string[]
            description: An array with the request types to include. An empty array means include all
            example: ["GetReservationByNativeReference", "QuoteBag"]

    responses:
        200:
          body:
            application/json:
              type: object
              properties:
                result:
                  type: string
                  example: "success"
                data:
                  type: object
                  example: |
                    {
                        "TestId": 23
                    }


/fusiontester/tests/statistics:
  get:
    description: Returns total number of tests, total number of FusionRequest records and total number of DCSrequests records

    responses:
        200:
          body:
            application/json:
              type: object
              properties:
                result:
                  type: string
                  example: "success"
                data:
                  type: object
                  example: |
                    {
                      "Tests" : 27,
                      "FusionRequests": 8342,
                      "DCSRequests": 12878
                    }

/fusiontester/airlines:
  get:
    description: Returns an array with the 2 letter codes of the airlines for which there is data  
          
    responses:
      200:
        body:
          application/json:
            type: array
            items: string
            
/fusiontester/airports:
  get:
    description: Returns an array with the 3 letter codes of the airports for which there is data  
          
    responses:
      200:
        body:
          application/json:
            type: array
            items: string
            
/fusiontester/fusion-request-types:
  get:
    description: Returns an array of the types of fusion requests for which there is data 
          
    responses:
      200:
        body:
          application/json:
            type: array
            items: string

/fusiontester/tests/{test-id}/results/statistics:
  get:
    description: Returns total number of records, total of successes and failures for the test with id test-id

    responses:
        200:
          body:
            application/json:
              type: object
              properties:
                result:
                  type: string
                  example: "success"
                data:
                  type: object
                  example: |
                    {
                      "TotalRecords" : 274,
                      "SuccessfulRecords": 214,
                      "FailedRecords": 60
                    }

/fusiontester/tests/{test-id}/results:
  get:
    description: Returns a page of results of a test
    queryParameters:
      page-size:
        type: integer
        description: Used for pagination. The number of records per page.
        required: false
        default: 10
        example: 12
      page:
        type: integer
        description: Used for pagination. The page number to return.
        required: false
        default: 1
        example: 3
        
    responses:
      200:
        body:
          application/json:
            type: array
            items: !include types/test-result.raml
    