#%RAML 1.0
title: FusionTester
version: v1
description: "Reads the Fusion requests from a table that has the logs of Fusion sesions and sends the requests to a Fusion service. It then compares the response from the Fusion service and compares it with the response in the log."

/fusiontester/execution:
  post:
    description: Starts a test providing its idea and possibly an indication that any previous run data should be deleted
    body:
      application/json:
        type: object
        properties:
          TestId:
            type: integer
            required: true
            example: 25
          Clean:
            type: boolean
            required: false
            default: true

    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              message:
                type: string
                example: |
                  {
                    "message" : "Test started"
                  }

/fusiontester/tests:
  get:
    description: Returns a list of tests. The tests returned can be filtered and paged.
    queryParameters:
      date-from:
        type: string
        required: false
        description: filters out tests done before this date
        example: '2019-05-04'
      date-to:
        type: string
        required: false
        description: filters out tests done after this date
        example: '2019-05-04'
      page-size:
        type: integer
        description: Used for pagination. The number of records per page.
        required: false
        default: 10
        example: 12
      page:
        type: integer
        description: Used for pagination. The page number to return.
        required: false
        default: 1
        example: 3
        
    responses:
      200:
        body:
          application/json:
            type: array
            items: !include types/test.raml
  post:
    description: Used for create new tests
    body:
      application/json:
        type: object
        properties:
          TestName:
            type: string 
            required: true
            description: Some meaningful name given to the test
            example: Regresion test for bug fix 12345
          TestDescription:
            type: string | nil
            required: false
            description: Text that provides information about the test
            example: Verify that the bug fix hasn't broken boarding for Jetblue
          TestCreator: 
            type: string | nil
            description: The name of the person that created the test
          IncludeAirports:
            type:  string[]
            description: An array with the 3 letter codes of the airports to include. An empty array means include all
            example: ["LHR","STN","EDI"]
          IncludeAirlines:
            type: string[]
            description: An array with the 2 letter codes of the airlines to include. An empty array means include all
            example: ["FR","BE","BA","LS"]
          FromDate:
            type: string | nil
            description: Used to filter the records to include in the test. This is the lower limit
            example: "2019-04-07 23:00:08"
          ToDate:
            type: string | nil
            description: Used to filter the records to include in the test. This is the upper limit
            example: "2019-09-07 02:00:08"
          IncludeFusionRequestTypes:
            type: string[]
            description: An array with the request types to include. An empty array means include all
            example: ["GetReservationByNativeReference", "QuoteBag"]

    responses:
        200:
          body:
            application/json:
              type: object
              properties:
                result:
                  type: string
                  example: "success"
                data:
                  type: object
                  example: |
                    {
                        "TestId": 23
                    }



/fusiontester/tests/{test-id}:
  get:
    description: Returns the records for test with specific TestId 
    queryParameters:
      page-size:
        type: integer
        description: Used for pagination. The number of records per page.
        required: false
        default: 10
        example: 12
      page:
        type: integer
        description: Used for pagination. The page number to return.
        required: false
        default: 1
        example: 3
        
    responses:
      200:
        body:
          application/json:
            type: array
            items: !include types/test-result.raml

  put:
    description: Used to update existing tests
    body:
      application/json:
        type: object
        properties:
          TestName:
            type: string 
            required: true
            description: Some meaningful name given to the test
            example: Regresion test for bug fix 12345
          TestDescription:
            type: string | nil
            required: false
            description: Text that provides information about the test
            example: Verify that the bug fix hasn't broken boarding for Jetblue
          TestCreator: 
            type: string | nil
            description: The name of the person that created the test
          IncludeAirports:
            type:  string[]
            description: An array with the 3 letter codes of the airports to include. An empty array means include all
            example: ["LHR","STN","EDI"]
          IncludeAirlines:
            type: string[]
            description: An array with the 2 letter codes of the airlines to include. An empty array means include all
            example: ["FR","BE","BA","LS"]
          FromDate:
            type: string | nil
            description: Used to filter the records to include in the test. This is the lower limit
            example: "2019-04-07 23:00:08"
          ToDate:
            type: string | nil
            description: Used to filter the records to include in the test. This is the upper limit
            example: "2019-09-07 02:00:08"
          IncludeFusionRequestTypes:
            type: string[]
            description: An array with the request types to include. An empty array means include all
            example: ["GetReservationByNativeReference", "QuoteBag"]

    responses:
        200:
          body:
            application/json:
              type: object
              properties:
                result:
                  type: string
                  example: "success"
                data:
                  type: object
                  example: |
                    {
                        "TestId": 23
                    }


/fusiontester/tests/statistics:
  get:
    description: Returns total number of tests, total number of FusionRequest records and total number of DCSrequests records

    responses:
        200:
          body:
            application/json:
              type: object
              properties:
                result:
                  type: string
                  example: "success"
                data:
                  type: object
                  example: |
                    {
                      "Tests" : 27,
                      "FusionRequests": 8342,
                      "DCSRequests": 12878
                    }

/fusiontester/airlines:
  get:
    description: Returns an array with the 2 letter codes of the airlines for which there is data  
          
    responses:
      200:
        body:
          application/json:
            type: array
            items: string
            
/fusiontester/airports:
  get:
    description: Returns an array with the 3 letter codes of the airports for which there is data  
          
    responses:
      200:
        body:
          application/json:
            type: array
            items: string
            
/fusiontester/fusion-request-types:
  get:
    description: Returns an array of the types of fusion requests for which there is data 
          
    responses:
      200:
        body:
          application/json:
            type: array
            items: string
    